name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Build Docker image
        run: docker build -t pypiserver .

      - name: Run Docker image
        run: |
          mkdir -p /tmp/pypiserver/packages
          docker run -d -p 8080:8080 -v /tmp/pypiserver/packages:/data/packages pypiserver

      - name: Test
        run: |
          sleep 5
          curl -s http://localhost:8080/simple/ | grep -q "Simple Index"
