name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build Docker image
        run: docker build -t pypiserver .

      - name: Run Docker image
        run: |
          mkdir -p /tmp/pypiserver/packages
          docker run -d -p 8080:8080 -v /tmp/pypiserver/packages:/data/packages pypiserver

      - name: Test
        run: curl -s http://localhost:8080/simple/ | grep -q "Simple Index"
