name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Build Docker image
        run: docker build -t pypiserver .

      - name: Run Docker image
        run: |
          mkdir -p /tmp/pypiserver/packages
          docker run -d -p 8080:8080 -v /tmp/pypiserver/packages:/data/packages pypiserver

      - name: Test
        run: |
          sleep 5
          curl -s http://localhost:8080/simple/ | grep -q "Simple Index"
