name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pypiserver .

      - name: Run Docker image
        run: docker run -d -p 8080:8080 pypiserver

      - name: Test
        run: curl -s http://localhost:8080/simple/ | grep -q "Index of /simple/"
